config/routes.rb
Cmumash::Application.routes.draw do
  get "stream/stream"

  get "user/student"

  get "home/index"

     match 'new' => 'stream#create', :as => :create
     match 'vote/:id' => 'stream#vote' ,:as => :vote
     match 'like/:stream/:user' => 'stream#hit_like' ,:as => :like
     match 'user/:id' => 'user#view' , :as => :user
     match 'img_check' => 'home#img_check' ,:as => :img_check

  root :to => 'home#index'

   match ':controller(/:action(/:id(.:format)))'
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  has_many :stream_votes
end

app/models/stream_vote.rb
class StreamVote < ActiveRecord::Base
  belongs_to :stream
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stream_votes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'open-uri'
  protect_from_forgery

  def student_img_checker(student_id)
    begin
      open("http://mis.cmu.ac.th/cmumis/images/student/#{student_id}.jpg") if User.find_by_student_id(student_id).nil?
    rescue
      nil
    else
      true
    end
  end

  def random_img
    r = Random.new
    year = r.rand(49...55).to_s
    department = r.rand(1...21).to_s
    major = [10,12,15][r.rand(0...3)].to_s
    last = r.rand(0...9).to_s + r.rand(0...9).to_s + r.rand(0...9).to_s
    rand = year+department+major+last
    if student_img_checker rand.to_i
      puts "found id: #{rand.to_i}"
      return rand
    else
      puts "fail id: #{rand.to_i}"
      random_img
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all.collect { |usr| usr.student_id  }
  end

  def img_check
    render :json => {:valid => student_img_checker(params[:id])}.to_json
  end


end

app/controllers/stream_controller.rb
class StreamController < ApplicationController

  def vote
    @students = []
    @likes = []
    begin
      @stream = Stream.find(params[:id])
      @stream.stream_votes.each do |vote|
        @students << User.find(vote.user_id).student_id
        @likes << vote.like
      end
    rescue
      redirect_to(create_url)
    end
  end

  def create
    @stream = Stream.new
    unless (params[:usr1].nil?||params[:usr2].nil?)
      begin
        if(student_img_checker(params[:usr1]) && student_img_checker(params[:usr2]))
          user1 = User.find_all_by_student_id(params[:usr1]).empty? ? User.create(:student_id => params[:usr1]) : User.find_by_student_id(params[:usr1])
          user2 = User.find_all_by_student_id(params[:usr2]).empty? ? User.create(:student_id => params[:usr2]) : User.find_by_student_id(params[:usr2])
          unless user1 == user2
            all_streams = user1.stream_votes.collect { |v| v.stream_id  }
            all_streams.each {|stream|
              redirect_to(vote_url(:id=>stream)) if StreamVote.find(:first , :conditions => ("user_id != #{user1.id} and stream_id = #{stream}")).user_id == user2.id
              return
            }
            @stream.save
            StreamVote.create(:stream_id=>@stream.id,:user_id=>user1.id)
            StreamVote.create(:stream_id=>@stream.id,:user_id=>user2.id)
            redirect_to(vote_url(:id=>@stream.id))
            return
          else
            redirect_to(create_url)
            return
          end
        end
      rescue
        redirect_to(create_url)
        return
      end
    end
  end

  def hit_like
    begin
      usr = User.find_by_student_id(params[:user])
      vote = StreamVote.find(:first, :conditions => {:stream_id => params[:stream], :user_id => usr})
      vote.like = vote.like+1
      vote.save
      redirect_to user_path(:id => params[:user])
    rescue
      redirect_to :back
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def view
    user = User.find_by_student_id(params[:id]) rescue nil
    if user.nil?
      if student_img_checker(params[:id])
        user = User.create :student_id => params[:id]
      else
        redirect_to :file => "404.html", :status => :not_found
        return
      end
    end
    @student = user.student_id
    @total_streams = user.stream_votes.count
    @total_likes = 0;
    user.stream_votes.each do |vote|
      @total_likes = @total_likes + vote.like if vote.like
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def student_img(student_id)
    "http://mis.cmu.ac.th/cmumis/images/student/#{student_id}.jpg"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/user_helper.rb
module UserHelper
  def render_likes_result likes
    likes>0 ? "#{likes} likes" : ""
  end
  def render_streams_result streams
    streams>0 ? "#{streams} times on stream" : ""
  end
end

app/views/home/index.html.erb
<div style="text-align: center; padding-top: 50px;">
  <h1>CMUMASH</h1>
  <p>Let's votes your college friends</p>
  <div style="margin: 80px">
    <%= link_to("Enjoy us!",create_path) %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cmumash</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/stream/create.html.erb
<script type="text/javascript">
  var loadImageRequest;
  function loadImage(student,side){
    var student_id = $(student).val()
    if(student_id.length>7){
      var url = "<%= img_check_path %>";

      if(loadImageRequest){
        loadImageRequest.abort();
      }

      loadImageRequest = $.ajax({
        type: "POST",
        url: url,
        data:{
          id: student_id
        },
        dataType: 'json',
        success: function(result){
          loadImageRequest = null;
          if(result.valid){
            if(side=="left"){
              $("#image_1").attr("src", "http://mis.cmu.ac.th/cmumis/images/student/"+student_id+".jpg");
            }else{
              $("#image_2").attr("src", "http://mis.cmu.ac.th/cmumis/images/student/"+student_id+".jpg");
            }
          }
          else{
            if(side=="left"){
              $("#image_1").attr("src","assets/mr_no.png");
            }else{
              $("#image_2").attr("src","assets/mr_no.png");
            }
            $(student).val("")
          }
        }
      });
    }
  }

</script>
<div style="text-align: center; padding-top: 20px">
  <h2>Let's make your friends popular</h2>
  <div style="width: 70%; margin: 80px auto auto auto;">
    <div class="container">
      <%= form_tag({:controller => "stream", :action => "create"}, :method => "get") do%>
        <div class="fivecol">
          <%= image_tag("mr_no.png",:id => "image_1", :class => "shadow", :height => 213, :width => 200 )%>
          <div style="margin-top: 20px;">
            <%= text_field_tag(:usr1,"",{:onBlur => "loadImage(this,'left');"}) %>
          </div>
        </div>
        <div class="twocol" style="margin-top: 100px">
          <h2>VS.</h2>
          <div style="margin-top: 150px;">
            <%= submit_tag("create") %>
          </div>
        </div>
        <div class="fivecol last">
          <%= image_tag("mr_no.png",:id => "image_2",:class => "shadow", :height => 213, :width => 200 )%>
          <div style="margin-top: 20px;">
            <%= text_field_tag(:usr2,"",{:onBlur => "loadImage(this,'right');"}) %>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/stream/vote.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $(".student_img").css("opacity","0.8");

    $(".student_img").hover(function () {
      $(this).stop().animate({
        opacity: 1.1
      }, "slow");
    },
    function () {
      $(this).stop().animate({
        opacity: 0.8
      }, "slow");
    });
  });


</script>

<div style="text-align: center; padding-top: 20px">
  <h2>Let's vote your friends</h2>
  <div style="width: 70%; margin: 80px auto auto auto;">
    <div class="container">
      <div class="fivecol">
        <a href="<%= like_path(@stream.id,@students[0])%>">
          <div class="student_img">
            <%= image_tag(student_img(@students[0]),
              :id => "student1",
              :height => 213,
              :width => 200
            )%>
            <p><%= render_likes_result @likes[0] %></p>
          </div>
        </a>
      </div>
      <div class="twocol" style="margin-top: 80px; font-size: 20px">
        <h2>VS.</h2>
      </div>
      <div class="fivecol last">
        <a href="<%= like_path(@stream.id,@students[1])%>">
          <div class="student_img">
            <%= image_tag(student_img(@students[1]),
              :id => "student2",
              :class => "shadow",
              :height => 213,
              :width => 200
            )%>
            <p><%= render_likes_result @likes[1] %></p>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/user/view.html.erb
<div style="text-align: center">

  <h1>Student id <%= @student %></h1>
  <div style="margin: 100px">
    <%= image_tag student_img(@student)%>
    <p><%= render_streams_result @total_streams %></p>
    <p><%= render_likes_result @total_likes %></p>
  </div>

</div>